name: Build

permissions:
  contents: write   # 🔥 BU ŞART

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Checkout Builds Branch
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds
          token: ${{ secrets.GITHUB_TOKEN }}   # 🔥 önemli

      - name: Clean old builds
        run: rm -f builds/*.cs3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew make makePluginsJson
          find . -name "*.cs3" -exec cp {} builds \;
          cp build/plugins.json builds || true

      - name: Push builds
        run: |
          cd builds
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Build $GITHUB_SHA" || echo "No changes"
          git push origin builds
